### ISSUE TITLE
can i add a default values 

### ISSUE THREAD

**Issue by cpliviu505** [cozeit/czMore#10]
i want to start with some default values of textbox

**Comment by yatabani** [comment]
Yes you can do that, the HTML template that you want to apply czMore to just needs to have the default value in it

**Comment by cpliviu505** [comment]
i want my page to be lfirst loades like that 
[https://imgur.com/Z76ft5N](url)

**Comment by yatabani** [comment]
This plugin repeats whatever HTML you give to it, so take the example you mentioned, if the <input value="3" /> then it's value will always be 3, but if what you want is to have it increment then you can implement that in the onAdd event..  hope this clears it 

happy coding

**Comment by cpliviu505** [comment]
i was add a new recordset but it's not working 
`    <div class="well clearfix">
        <div id="czContainer">
            <div id="first">

                <div class="recordset">
                    <div class="fieldRow clearfix">
                        <div class="col-md-5">
                            <div id="div_id_stock_1_service" class="form-group">
                                <label for="id_stock_1_product" class="control-label  requiredField">
                                    Product<span class="asteriskField">*</span>
                                </label><div class="controls ">
                                            <input type="text" name="stock_1_product" id="id_stock_1_product" class="textinput form-control" />
                                </div>
                            </div>
                        </div>


                    </div>

                <div class="recordset">
                    <div class="fieldRow clearfix">
                        <div class="col-md-5">
                            <div id="div_id_stock_1_service" class="form-group">
                                <label for="id_stock_1_product" class="control-label  requiredField">
                                    Product<span class="asteriskField">*</span>
                                </label><div class="controls ">
                                            <input type="text" name="stock_1_product" id="id_stock_1_product" class="textinput form-control" />
                                </div>
                            </div>
                        </div>


                    </div>
                </div>
            </div>
        </div>
    </div>
`

**Comment by yatabani** [comment]
```
<input value="3" />
```

Does it work at all for you

**Comment by yatabani** [comment]
I will consider this issue closed, as there is no more comment
