### ISSUE TITLE
Max Limit Alert Pop Up

### ISSUE THREAD

**Issue by najeeb2113** [cozeit/czMore#11]
can any one help me for how to show a pop up when 
max: 5
is reached
like 'Max limit reached'
$("#czContainer").czMore({
    max: 5
});
How and where

**Comment by najeeb2113** [comment]
ok had sorted it  out by adding alert in its czmore.js

**Comment by yatabani** [comment]
This is a nice use for it, probably needs to be added as built-in function. 

You can add it now on the onAdd event
```
$("#czContainer").czMore({
    onAdd: function(index) {
        if (index > 4){
            alert('Max limit reached');
        }
    }
});
```
I didn't test that but it should work, let me know how it works for you

all the best

**Comment by yatabani** [comment]
Go ahead and Fork this repo and make a Pull Request with your changes, anytime
