### ISSUE TITLE
How do you add previously saved values?

### ISSUE THREAD

**Issue by prateekshaweb** [cozeit/czMore#3]
How do you add previously saved values?
I have saved some values saves in the database...i need to load them in the initial rows...
how do I do that?...
how do I trigger onAdd event with these values

**Comment by yatabani** [comment]
I would recommend you use normal iteration for that, to load the saved values into the given html, if you want to do that using the `onAdd` event that's fine, although you would have to accommodate for the event of when one of those rows is deleted.

here is how you can override the `onAdd` event
```
$("#czContainer").czMore({
        onAdd: function() {
            $("#input").val("yourvalue");
            ... etc
       },
});
```

I would recommend you load the saved data normally by other means and include the `data-id` attribute on the `recordset` that way you can override the `onDelete` event, which will pass the given `data-id` as a parameter so you can take it from there.
