### ISSUE TITLE
Setting maximum number of fields

### ISSUE THREAD

**Issue by oleteacher** [cozeit/czMore#5]
Hey, nice plugin!

Is there way to set the maximum number of fields that can be added?

Thanks.

**Comment by yatabani** [comment]
Hi, Thanks

No this feature is not implemented, you can go ahead and add a condition to the add event, and implement it, I will have to problem adding it to the plugin

**Comment by oleteacher** [comment]
Thanks for reply.

I attempted to add condition (limit number) and failed to get working. Been so long ago, forgot exactly what I did and what did not work.

Be a great feature if you find time to implement:)

Cheers!

**Comment by yatabani** [comment]
Here you go, you can now use this feature

```javascript
$("#czContainer").czMore({
    max: 5
});
```

Enjoy!

**Comment by oleteacher** [comment]
Thank you, very nice of you to implement. Very useful feature:)

**Comment by najeeb2113** [comment]
> Here you go, you can now use this feature
> 
> ```js
> $("#czContainer").czMore({
>     max: 5
> });
> ```
> 
> Enjoy!

sir is there any way to send a popup message 'limit exceeded' when limit is reached and user try to add more
