### ISSUE TITLE
select2 + czMore problem

### ISSUE THREAD

**Issue by kindaniel** [cozeit/czMore#6]
Select2 new fields for CzMore is not working. in the field that is not created with czMore is working, the add on method onAdd does not work. Any idea?

**Comment by yatabani** [comment]
You need to hookup select2, on the onAdd event

**Comment by yatabani** [comment]
Hope this helps
```
$("#czContainer").czMore({
        onAdd: function() {
            $("input[id$='_suffex']").select2();
        }
});
```

**Comment by yatabani** [comment]
duplicate of issue number #4

**Comment by yatabani** [comment]
please refer to http://yatabani.com/Integrating-Select2-with-czMore/
